### PR TITLE
Add KasmVNC and custom commands

### PR DESCRIPTION
**Pull request by Biont**
Hello! 

I've been following your footsteps and those of @deviantintegral over at https://github.com/deviantintegral/ddev-playwright in my quest for a clean, ready-to-use Playwright setup.
I believe your approach using an actual, separate docker service is the cleaner one. However, @deviantintegral 's solution has the ability to run in UI/headed mode with its VNC server - which is something I really want to see.
Plus, with this being an actual addon service, it is very easy to `ddev service enable|disable playwright` - making all the conditional logic of the other approach uneeded. So this ends up being quite a bit smaller and less complex.

I know there's some discovery and history to each solution, but I saw no reason why VNC could not be added to a dedicated DDEV service, so I gave it a shot. Maybe there is some key feature I am missing which is not possible in such a setup, but my testing suggests that everything is running fine.

I also added a few commands for convenience - as well as a rudimentary setting for configuring the test directory.

If you like these changes, please consider merging this PR

### CODE REVIEW

**Comment by julienloizelet** [comment]
Thanks for this PR.

I guess I'm not using Playwright the right way: I use Jest for test instead of playwright/test.

Thus, I first need to use Playwright as recommended (it could take some times to change my way of doing in multiple projects...)

Then, I will give a try to your PR.

I just have one question for the moment :

-  I looked to the https://github.com/deviantintegral/ddev-playwright repo and saw that Traefik is mandatory to use kasmVNC : https://github.com/deviantintegral/ddev-playwright/blob/main/README.md?plain=1#L36 . Do you confirm that it works only with traefik ?

Thanks

**Comment by Biont** [comment]
>Do you confirm that it works only with traefik ?
I have not explicitly tested if if works _without_ it. That's just a thing I've verified when I first tried the other solution

There's a few other things that are worth mentioning:

* Due to Playwright's nature of coupling its runtime tightly to its test utils, it is sometimes challenging to come up with a  generic solution: Setting up playwright for execution via generic commands is very tough if you want to accomplish zero assumptions about the test project. While I managed to provide at least some rudimentary way of changing the test directory so it suits any project, I could not get rid of the fact that our company work requires sourcing a BASE_URL from an `.env` file. This is still reflected in the install command and I failed to mention it in the OP. I think it is a valuable thing to do (it allows us to specify/change the host URL when running ngrok in CI), but other developers will have vastly different approaches here. If you know a solution to this, let me know.
* The BATS tests still use handwritten `yarn` commands while they could probably already use the `ddev playwright` commands. That would put those under test as well. I wanted to keep the PR small, so that is something we could look at when you have a clearer view
* The playwright container runs as `root` which is probably something we could sort out, but I was too lazy to figure out how DDEV determines the `$username` and whether this is somehow supplied to custom services. I need to check this out because it is annoying not to have write permissions to the installed dependencies

**Comment by Biont** [comment]
I am strictly unwilling to admit how much time it took to get this running. But now tests are passing (even on GHA) and the following changes have been made.

1. Tests are now actually using the `ddev playwright` commands
2. The VNC connection is superficially tested as well
3. VNC no longer requires basic auth
4. The internal BATS test is actually using a proper playwright config now - using the aforementioned `.env` workflow

@julienloizelet

**Comment by deviantintegral** [comment]
> I guess I'm not using Playwright the right way: I use Jest for test instead of playwright/test.

Eh, I think that's more complicated, but I don't think it's wrong! If you or your team is comfortable with Jest, it seems reasonable to me. Are you using https://github.com/playwright-community/jest-playwright ?

>  I could not get rid of the fact that our company work requires sourcing a BASE_URL from an .env file

We're pulling in environment variables into playwright.config.ts. There's a commented out part at the top of the default config? In our case, we use:

```
require('dotenv').config({
  path: '../../.env',
});
```

I don't see why the playwright baseURL couldn't be set from this.

Anyways, nice work! I'll be watching this!

**Comment by julienloizelet** [comment]
Thanks @deviantintegral for your message; Well as it is recommended by the repo itself https://github.com/playwright-community/jest-playwright#%EF%B8%8F-we-recommend-the-official-playwright-test-runner-playwrighttest-%EF%B8%8F, I guess i have to move from jest-playwright to playwright. I just hope the "migration" doesn't hurt too much :) 

And thanks @Biont for your work, I will try it asap.

**Comment by julienloizelet** [comment]
Hi @Biont , it looks good to me.

 I did not have time to change all my playwright/jest workflows to playwright workflow (it's like a new world...) but  I was able to test that:
 - your simple example test works
 - my old playwright/jest tests are not broken (just have to handle the new "working_dir" that points now to `/var/www/html`)
 - ksamvnc seems to work without traefik too
 
 
 There is just one thing that doesn't work for me : https://<PROJECT>.ddev.site:9324 should show report test but failed (bad gateway). 
 `ddev playwright show-report` failed too. Maybe it is related to [this](https://github.com/microsoft/playwright/issues/16667) but I have no idea.
 If you have any idea, please let me know. Otherwise, as I guess this is not something really important, maybe I would just remove all that is related to the 9323,9324 ports exposition.
 
 Thanks

**Comment by Biont** [comment]
@julienloizelet 
>https://.ddev.site:9324 should show report test but failed (bad gateway).
ddev playwright show-report failed too. 


I needed to fix the ports, but what really made it work is opening the web server using `ddev playwright show-report --host 0.0.0.0`(specifying/overriding the host). I could not find a playwright config to force this setting (though I did not fail to notice that [I am again just following @deviantintegral 's trail here](https://github.com/microsoft/playwright/discussions/20986#discussioncomment-5123363) )

For now, this appears to be something we'll just have to live with, I guess. Docs should be added stating that the ` --host 0.0.0.0` param is needed

**Comment by Biont** [comment]
@deviantintegral 
>We're pulling in environment variables into playwright.config.ts. There's a commented out part at the top of the default config?

I was just pointing at [this annoying little line here](https://github.com/Biont/ddev-playwright/blob/0e4a1b90011a2e1bbdc7ad0d43178e2b5eed6513/commands/playwright/playwright-install#L16). Based on the assumption that `ddev playwright-install` SHOULD result in a usable setup, placing that `.env` file needed to be handled _somewhere_.

However, this is not something I would want a _generic_ playwright addon to impose on its users. I added a conditional around it for now.

**Comment by julienloizelet** [comment]
Hi @Biont , I just merged all of your work and add some documentation.

Please let me know if all seems good to you. 

If there is no other important update, I will release a 2.0.0 of the add-on that will embed of all this new stuff.

Thanks again.

**Comment by Biont** [comment]
@julienloizelet Thank you for taking care of the great documentation and for being so open-minded in general. I know these _"watlzing in and turning a project inside out"_ types of PRs are not always a guaranteed success and I try to avoid them normally.

 >If there is no other important update, I will release a 2.0.0 
At the very least, I can say that I did not _plan_ on adding more stuff for now. There's always room for improvements, but we've reached a good point where we can draw a line. I will create an issue with _that one last thing_ I had in mind.

**Pull request merged**
